# Generated by me on Django 4.1.5 on 2023-01-17 10:29

# Migrate from django FileField to DynamicFieldFile is not supported yet
# so first delete all records, then rm FileField and finally add DynamicFieldFile

from django.db import migrations
import wagtail.images.models
import say.dynamic_storage.models


def delete_all_renditions(apps, schema_editor):
    DSWRendition = apps.get_model("core", "DSWRendition")
    DSWRendition._default_manager.all().delete()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_dsws"),
    ]

    operations = [
        migrations.RunPython(delete_all_renditions, do_nothing),
        migrations.RemoveField(model_name="dswrendition", name="file"),
        migrations.AddField(
            model_name="dswrendition",
            name="file",
            field=say.dynamic_storage.models.DynamicImageField(
                height_field="height",
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
