# Generated by Django 4.1.3 on 2022-12-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0081_alter_collectionviewrestriction_groups_and_more"),
        ("user_manager", "0002_siteuser_siteuser_unique_site_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="site_project",
                        serialize=False,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
