# Generated by Django 4.1.1 on 2022-09-08 05:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("super_page", "0004_delete_telegramactionorderable_and_more"),
        ("linked_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramaction",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="telegramaction",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="telegramaction",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_telegramactions",
                to="super_page.simplepage",
            ),
        ),
    ]
