# Generated by Django 4.1.1 on 2022-09-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linked_account", "0002_alter_telegramaction_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramaction",
            name="telegram_instance",
        ),
    ]
