# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webpage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwebpage.proto\x12\x07webpage\"%\n\tSuperPage\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\"\x19\n\x06Result\x12\x0f\n\x07message\x18\x01 \x01(\t2C\n\x07Publish\x12\x38\n\x0fPublishRichText\x12\x12.webpage.SuperPage\x1a\x0f.webpage.Result\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')



_SUPERPAGE = DESCRIPTOR.message_types_by_name['SuperPage']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
SuperPage = _reflection.GeneratedProtocolMessageType('SuperPage', (_message.Message,), {
  'DESCRIPTOR' : _SUPERPAGE,
  '__module__' : 'webpage_pb2'
  # @@protoc_insertion_point(class_scope:webpage.SuperPage)
  })
_sym_db.RegisterMessage(SuperPage)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'webpage_pb2'
  # @@protoc_insertion_point(class_scope:webpage.Result)
  })
_sym_db.RegisterMessage(Result)

_PUBLISH = DESCRIPTOR.services_by_name['Publish']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _SUPERPAGE._serialized_start=26
  _SUPERPAGE._serialized_end=63
  _RESULT._serialized_start=65
  _RESULT._serialized_end=90
  _PUBLISH._serialized_start=92
  _PUBLISH._serialized_end=159
# @@protoc_insertion_point(module_scope)
