# Generated by Django 4.1.3 on 2022-12-03 14:30

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_manager", "0002_project_projectuser_projectuser_unique_project_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="name")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="permission_projectgroups",
                        to="auth.permission",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_projectgroups",
                        to="user_manager.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "swappable": "AUTH_GROUP_MODEL",
            },
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="projectgroup",
            constraint=models.UniqueConstraint(
                fields=("name", "project"), name="unique_name_project"
            ),
        ),
    ]
