# Generated by Django 4.1.3 on 2022-12-03 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_manager", "0003_projectgroup_projectgroup_unique_name_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="projectgroup_projectusers",
                to=settings.AUTH_GROUP_MODEL,
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="permission_projectusers",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
