# Generated by Django 4.1.1 on 2022-09-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("linked_account", "0003_remove_telegramaction_telegram_instance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramInstance",
        ),
    ]
