# Generated by Django 4.2.1 on 2023-05-18 15:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0086_alter_site_root_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListablePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ListingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("editor", wagtail.blocks.RichTextBlock())],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "listablepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="page_types.listablepage",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("editor", wagtail.blocks.RichTextBlock())],
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("page_types.listablepage",),
        ),
        migrations.AddField(
            model_name="listablepage",
            name="listings",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="A reference to this page appear in witch ListablePages",
                related_name="listingpage_pages",
                to="page_types.listingpage",
            ),
        ),
    ]
