# Generated by Django 4.1.5 on 2023-01-27 23:09

from django.db import migrations, models
import django.db.models.deletion
import say.storage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0081_alter_collectionviewrestriction_groups_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=63,
                        validators=[say.storage.models.available_storage_validator],
                    ),
                ),
                ("title", models.CharField(max_length=127)),
                ("args", models.JSONField(default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
        ),
    ]
