# Generated by Django 4.2.1 on 2023-05-07 20:29

from django.db import migrations
import say.accounting.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0003_project"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", say.accounting.models.UserManager()),
            ],
        ),
    ]
