# Generated by Django 4.1 on 2022-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super_page", "0002_telegraminstance_telegrampublishmode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegraminstance",
            name="chat_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
