# Generated by Django 4.1.1 on 2022-09-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("super_page", "0003_telegraminstance_chat_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramActionOrderable",
        ),
        migrations.DeleteModel(
            name="TelegramInstance",
        ),
        migrations.DeleteModel(
            name="TelegramPublishMode",
        ),
    ]
